# This is a Docker Compose file for setting up a HAProxy tunnel with a SOCKS5 proxy.
services:
  hatunnel:
    build: .
    container_name: hatunnel
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8888:8888"
    environment:
      - SOCKS5_PROXY=196.16.110.34:8000
      - PROXY_USER=koTHWe
      - PROXY_PASS=u0b8yD
    volumes:
      - ./logs:/var/log/haproxy
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8080 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3